In [1]:
import sys
import os
sys.path.append(os.path.abspath(".."))

import pandas as pd

from src.data.market_loader import MarketLoader

In [2]:
# downloading market curves
loader = MarketLoader()

treasury_curve = loader.load_curve('treasury')
sofr_curve = loader.load_curve('sofr')
money_market = loader.load_curve('money_market')

treasury curve dataset already downloaded..
sofr curve dataset already downloaded..
money_market curve dataset already downloaded..

When constructing zero curve, we will be using overnight rates as the starting point and fed funds as the expectations. 

Treasury yields will constitute the long-end of the curve.

In [3]:
treasury_curve

              1M    3M    6M    1Y    2Y    5Y   10Y   30Y
Date
2001-07-31  3.67  3.54  3.47  3.53  3.79  4.57  5.07  5.51
2001-08-01  3.65  3.53  3.47  3.56  3.83  4.62  5.11  5.53
2001-08-02  3.65  3.53  3.46  3.57  3.89  4.69  5.17  5.57
2001-08-03  3.63  3.52  3.47  3.57  3.91  4.72  5.20  5.59
2001-08-06  3.62  3.52  3.47  3.56  3.88  4.71  5.19  5.59
...          ...   ...   ...   ...   ...   ...   ...   ...
2026-04-03  3.71  3.71  3.73  3.72  3.84  3.99  4.35  4.91
2026-04-06  3.72  3.72  3.74  3.72  3.84  3.98  4.34  4.89
2026-04-07  3.68  3.71  3.73  3.68  3.81  3.95  4.33  4.90
2026-04-08  3.67  3.69  3.73  3.69  3.79  3.92  4.29  4.89
2026-04-09  3.66  3.68  3.71  3.68  3.78  3.91  4.29  4.90

[6443 rows x 8 columns]

In [4]:
treasury_curve.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 6443 entries, 2001-07-31 to 2026-04-09
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   1M      6174 non-null   float64
 1   3M      6174 non-null   float64
 2   6M      6174 non-null   float64
 3   1Y      6174 non-null   float64
 4   2Y      6174 non-null   float64
 5   5Y      6174 non-null   float64
 6   10Y     6174 non-null   float64
 7   30Y     6174 non-null   float64
dtypes: float64(8)
memory usage: 453.0 KB

In [5]:
sofr_curve

              ON  FEDFUNDS
Date
2018-04-03  1.83       NaN
2018-04-04  1.74       NaN
2018-04-05  1.75       NaN
2018-04-06  1.75       NaN
2018-04-09  1.75       NaN
...          ...       ...
2026-04-06  3.65       NaN
2026-04-07  3.62       NaN
2026-04-08  3.59       NaN
2026-04-09  3.57       NaN
2026-04-10  3.61       NaN

[2094 rows x 2 columns]

In [6]:
sofr_curve.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 2094 entries, 2018-04-03 to 2026-04-10
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ON        2003 non-null   float64
 1   FEDFUNDS  67 non-null     float64
dtypes: float64(2)
memory usage: 49.1 KB

In [7]:
sofr_curve.loc[~sofr_curve['FEDFUNDS'].isnull()]

              ON  FEDFUNDS
Date
2018-05-01  1.76      1.70
2018-06-01  1.81      1.82
2018-08-01  1.88      1.91
2018-10-01  2.22      2.19
2018-11-01  2.22      2.20
...          ...       ...
2025-08-01  4.34      4.33
2025-09-01   NaN      4.22
2025-10-01  4.20      4.09
2025-12-01  4.12      3.72
2026-01-01   NaN      3.64

[67 rows x 2 columns]

In [8]:
money_market

            TBill3M  TBill6M
Date
1954-01-04     1.33      NaN
1954-01-05     1.28      NaN
1954-01-06     1.28      NaN
1954-01-07     1.31      NaN
1954-01-08     1.31      NaN
...             ...      ...
2026-04-03     3.62     3.61
2026-04-06     3.64     3.62
2026-04-07     3.62     3.60
2026-04-08     3.61     3.60
2026-04-09     3.60     3.58

[18854 rows x 2 columns]

In [9]:
money_market.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 18854 entries, 1954-01-04 to 2026-04-09
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   TBill3M  18058 non-null  float64
 1   TBill6M  16818 non-null  float64
dtypes: float64(2)
memory usage: 441.9 KB